#!/usr/bin/env bash

cd -- "$( dirname -- "${BASH_SOURCE[0]}" )"

rm -rf ./pkg/api
mkdir -p ./pkg/api

protoc --go_out=./pkg/api --go_opt=paths=source_relative --go-grpc_out=./pkg/api --go-grpc_opt=paths=source_relative $(find ./proto -iname "*.proto") --proto_path=./proto
