// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/asaskevich/EventBus"
	"github.com/wireless-monkeys/backend/pkg/api"
	"github.com/wireless-monkeys/backend/pkg/config"
	"github.com/wireless-monkeys/backend/pkg/service"
	"google.golang.org/grpc"
)

// Injectors from wire.go:

func InitializeServer() *grpc.Server {
	configConfig := config.NewConfig()
	bus := EventBus.New()
	dashboardServiceServer := service.NewDashboardServiceServer(configConfig, bus)
	edgeServiceServer := service.NewEdgeServiceServer(bus)
	helloServiceServer := service.NewHelloServiceServer()
	server := provideGrpcServer(dashboardServiceServer, edgeServiceServer, helloServiceServer)
	return server
}

// wire.go:

func provideGrpcServer(
	dashboardService api.DashboardServiceServer,
	edgeService api.EdgeServiceServer,
	helloService api.HelloServiceServer,
) *grpc.Server {
	s := grpc.NewServer()
	api.RegisterDashboardServiceServer(s, dashboardService)
	api.RegisterEdgeServiceServer(s, edgeService)
	api.RegisterHelloServiceServer(s, helloService)
	return s
}
